### Домашка №5


**1 задача**

In [1]:
import numpy as np

In [2]:
x=10
empty_list=[]
while x>=0:
    empty_list.append(x)
    x-=1
np.array(empty_list)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [3]:
y=np.arange(0,10)
y[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [7]:
z=np.flip(y)
z

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Как итог, быстрее всего наверно сделать так:

In [10]:
array_1=np.flip(np.arange(0,10))
array_1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задача 2**

In [12]:
N=10
x = np.eye(N)
total = 0
Y=N
for i in range(0, N):
    x[i][i]=Y 
    total += x[i][i]
    Y-=1
print(x)
print(total)

[[10.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  9.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  8.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  7.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  6.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  4.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  3.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]
55.0


**Задача 3** <br>
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.


In [5]:
import pandas as pd
ratings=pd.read_csv('ratings.csv', sep=',')
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [6]:
ratings[(ratings['rating']==5)].groupby('movieId').rating.count().reset_index(name='count').sort_values(['count'], ascending=False).head(10)

movieId  count
174       318    153
161       296    123
198       356    116
1052     2571    109
140       260    104
269       527     92
294       593     92
375       858     88
1173     2959     81
66        110     80

<font color='red'>Насколько корректна такая запись, оптимальна ли она и если да, то как записывать такой код, чтобы можно было читабельно для других, ведь если запрос куда длиннее, то невозможно уследить, особенно с количеством фильтров как в 4 задаче</font>

**Задача 4** <br>
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [7]:
power=pd.read_csv('power.csv', sep=',')
power.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [16]:
power[((power['country']=='Latvia') | (power['country']=='Lithuania') | (power['country']=='Estonia')) 
           & ((power['year']>=2005) & (power['year']<=2010)) & ((power['category'].isin)([4,12,21]) ) & (power['quantity']>0)]['quantity'].sum()



240580.0

<font color='red'>В этой задаче как-то можно ограничить столбец суммирования? Чтобы на выходе было только quantity - sum. Я попытался найти, не нашёл :(</font> 


**Задача 5**

4x + 2y + z = 4 <br>
x  + 3y + 0z = 12 <br>
0x + 5y + 4z = -3

In [23]:
M1 = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]]) # Матрица (левая часть системы)
v1 = np.array([4, 12, -3]) # Вектор (правая часть системы)
np.linalg.solve(M1, v1)

array([ 0.46666667,  3.84444444, -5.55555556])